<template>
  <div>
    <div class="snow1" style="width: 32.9213px; position: fixed; left: 171.559px; animation-name: toright; top: -20px; animation-duration: 7.61945s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img src="../../../img/t1003/hongbao3.png" style="animation-name: rotate; animation-duration: 4.7084s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 30.7009px; position: fixed; left: 35.6629px; animation-name: toright; top: -20px; animation-duration: 6.10232s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/yuanbao3.png" style="animation-name: rotate; animation-duration: 4.21603s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 30.1644px; position: fixed; left: 180.317px; animation-name: toright; top: -20px; animation-duration: 7.84105s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img src="../../../img/t1003/hongbao3.png" style="animation-name: clock; animation-duration: 5.45985s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 32.5366px; position: fixed; left: 67.0433px; animation-name: toright; top: -20px; animation-duration: 4.21683s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img   src="../../../img/t1003/hongbao2.png" style="animation-name: clock; animation-duration: 5.52401s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 32.6324px; position: fixed; left: 241.392px; animation-name: toright; top: -20px; animation-duration: 6.62498s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/yuanbao2.png" style="animation-name: rotate; animation-duration: 5.46145s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 32.3647px; position: fixed; left: 115.904px; animation-name: toright; top: -20px; animation-duration: 5.2338s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/hongbao3.png" style="animation-name: clock; animation-duration: 5.70188s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 32.861px; position: fixed; left: -17.0053px; animation-name: toright; top: -20px; animation-duration: 5.13252s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/yuanbao4.png" style="animation-name: rotate; animation-duration: 5.04182s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 30.7838px; position: fixed; left: 169.059px; animation-name: toleft; top: -20px; animation-duration: 4.9048s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img   src="../../../img/t1003/hongbao2.png" style="animation-name: rotate; animation-duration: 4.10549s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 30.0871px; position: fixed; left: 122.779px; animation-name: toleft; top: -20px; animation-duration: 4.42572s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/yuanbao4.png" style="animation-name: rotate; animation-duration: 3.90611s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 34.1128px; position: fixed; left: -51.0456px; animation-name: toright; top: -20px; animation-duration: 7.6504s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img   src="../../../img/t1003/hongbao2.png" style="animation-name: clock; animation-duration: 2.51709s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 31.4628px; position: fixed; left: 237.136px; animation-name: toleft; top: -20px; animation-duration: 7.43637s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img   src="../../../img/t1003/hongbao2.png" style="animation-name: rotate; animation-duration: 5.81697s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 31.6923px; position: fixed; left: 91.1671px; animation-name: toleft; top: -20px; animation-duration: 4.2153s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img   src="../../../img/t1003/hongbao1.png" style="animation-name: rotate; animation-duration: 4.95694s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 32.5492px; position: fixed; left: 154.789px; animation-name: toright; top: -20px; animation-duration: 6.17117s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/yuanbao2.png" style="animation-name: rotate; animation-duration: 4.12638s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 32.0471px; position: fixed; left: 132.171px; animation-name: toleft; top: -20px; animation-duration: 6.28249s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/hongbao2.png" style="animation-name: rotate; animation-duration: 4.00007s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 31.4658px; position: fixed; left: -20.4158px; animation-name: toright; top: -20px; animation-duration: 7.89975s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/hongbao3.png" style="animation-name: rotate; animation-duration: 5.83255s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 31.1035px; position: fixed; left: 123.856px; animation-name: toright; top: -20px; animation-duration: 4.21001s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/hongbao3.png" style="animation-name: clock; animation-duration: 2.43492s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 32.6267px; position: fixed; left: -52.3247px; animation-name: toright; top: -20px; animation-duration: 7.47147s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img  src="../../../img/t1003/hongbao3.png" style="animation-name: rotate; animation-duration: 2.83094s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 30.094px; position: fixed; left: 122.184px; animation-name: toleft; top: -20px; animation-duration: 5.42886s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img   src="../../../img/t1003/hongbao1.png" style="animation-name: clock; animation-duration: 5.66451s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
    <div class="snow1" style="width: 33.9872px; position: fixed; left: 161.978px; animation-name: toleft; top: -20px; animation-duration: 4.06774s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;"><img   src="../../../img/t1003/yuanbao4.png" style="animation-name: rotate; animation-duration: 4.92978s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;"></div>
  </div>
</template>
