<template>
  <div>
    <div class="snow1" style="width: 23.4196px; position: fixed; left: 304.734px; animation-name: toleft; top: -30px; animation-duration: 12.1878s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:2.5s;">
      <img src="https://ss2.meipian.me/theme/v2/img/snow_1.png" style="animation-name: rotate; animation-duration: 2.52731s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
    </div><div class="snow1" style="width: 21.5607px; position: fixed; left: 113.832px; animation-name: toright; top: -30px; animation-duration: 12.6421s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:4.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_2.png" style="animation-name: rotate; animation-duration: 5.9037s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 25.5273px; position: fixed; left: 212.487px; animation-name: toright; top: -30px; animation-duration: 14.1989s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:0.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_3.png" style="animation-name: rotate; animation-duration: 5.19324s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 19.0391px; position: fixed; left: 170.02px; animation-name: toright; top: -30px; animation-duration: 14.2174s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:6.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_1.png" style="animation-name: rotate; animation-duration: 2.80874s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 25.549px; position: fixed; left: 348.137px; animation-name: toleft; top: -30px; animation-duration: 12.5519s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:2.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_1.png" style="animation-name: clock; animation-duration: 2.0345s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 28.3392px; position: fixed; left: 332.552px; animation-name: toleft; top: -30px; animation-duration: 12.3922s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:1s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_3.png" style="animation-name: clock; animation-duration: 4.1484s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 21.8988px; position: fixed; left: 19.2856px; animation-name: toright; top: -30px; animation-duration: 13.3503s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:0.8s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_1.png" style="animation-name: rotate; animation-duration: 5.63993s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 19.7988px; position: fixed; left: 49.5017px; animation-name: toleft; top: -30px; animation-duration: 14.2378s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:9.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_1.png" style="animation-name: clock; animation-duration: 5.37576s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 28.5866px; position: fixed; left: 244.922px; animation-name: toleft; top: -30px; animation-duration: 13.1545s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:8s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_2.png" style="animation-name: rotate; animation-duration: 5.24331s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 18.6831px; position: fixed; left: 237.614px; animation-name: toleft; top: -30px; animation-duration: 12.8093s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:7.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_3.png" style="animation-name: rotate; animation-duration: 2.19395s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 26.2226px; position: fixed; left: 150.946px; animation-name: toright; top: -30px; animation-duration: 13.629s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:2.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_3.png" style="animation-name: rotate; animation-duration: 3.94233s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 20.702px; position: fixed; left: 89.86px; animation-name: toleft; top: -30px; animation-duration: 14.3145s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:1.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_1.png" style="animation-name: rotate; animation-duration: 3.23592s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 27.1629px; position: fixed; left: 133.052px; animation-name: toleft; top: -30px; animation-duration: 15.5285s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:6.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_3.png" style="animation-name: clock; animation-duration: 3.83017s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 26.2147px; position: fixed; left: 311.576px; animation-name: toleft; top: -30px; animation-duration: 14.5332s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:11.5s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_3.png" style="animation-name: rotate; animation-duration: 4.7392s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div><div class="snow1" style="width: 19.4604px; position: fixed; left: 104.032px; animation-name: toleft; top: -30px; animation-duration: 13.4167s; animation-iteration-count: infinite; animation-timing-function: linear; z-index: 11;animation-delay:4s;">
    <img src="https://ss2.meipian.me/theme/v2/img/snow_1.png" style="animation-name: clock; animation-duration: 2.37973s; animation-iteration-count: infinite; animation-timing-function: ease-in-out; animation-direction: alternate; width: 100%; height: 100%;">
  </div>
  </div>
</template>
